#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" == "develop" ]; then
  echo "🚨 No podés commitear directamente en develop. Creá una rama nueva."
  exit 1
fi

if [ "$branch" == "master" ]; then
  echo "🚨 No podés commitear directamente en master. Tenés que trabajar en una rama nueva desde develop y generar la PR apuntando a develop."
  exit 1
fi