name: Build Android APK

on:
  push:
    branches:
      - main  # Cambiá si usás otra rama principal

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: List generated APKs
        run: ls -R app/build/outputs/apk/

      - name: Rename APK
        run: |
          mkdir -p output
          cp app/build/outputs/apk/release/app-release.apk output/app-${{ github.run_number }}.apk

      - name: Version tag
        id: version
        run: echo "version=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: output/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
