name: Prerelease APK on Dev Merge

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Signed APK and Prerelease
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore from base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build unsigned APK
        run: ./gradlew assembleRelease

      - name: Align APK (zipalign)
        run: |
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
            app/build/outputs/apk/release/app-pre-release-unsigned.apk \
            app-pre-release-aligned.apk

      - name: Sign APK with apksigner
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks my-release-key.keystore \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out app-pre-release.apk \
            app-pre-release-aligned.apk

      - name: Verify APK signature
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner verify --verbose app-pre-release.apk

      - name: Generate version tag
        id: versioning
        run: |
          VERSION_TAG="prerelease-$(date +'%Y.%m.%d.%H%M')"
          echo "version=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Commit & Tag version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.versioning.outputs.version }}
          git push origin ${{ steps.versioning.outputs.version }}

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          name: Dev Prerelease ${{ steps.versioning.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: app-pre-release.apk
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
